### ISSUE TITLE
font-प्रश्नः

### ISSUE THREAD

**Issue by vvasuki** [aupasana/prayoga#13]
https://github.com/aupasana/prayoga/blob/master/font.md इत्यस्य किं कारणम्? कुतो न web-fonts इति प्रयुङ्क्षे? ननु https://sanskrit-coders.github.io/site/pages/content/fonts/1-notosans-devanagari-github.html इति तवैवोदाहरणम्?

**Comment by aupasana** [comment]
http://aupasana.com/prayoga/font-test.html

See if all the combinations in the page above render correctly for you with noto. They don't for me. Chrome and Siddhanta (except on iOS) is predictable.

**Comment by vvasuki** [comment]
webfonts-प्रयोगो नाम noto-प्रयोग इति न भोः - सिद्धान्ताक्षरमुखमेव प्रयुङ्ग्धि। तद्यथा - <https://sanskrit-coders.github.io/site/pages/content/fonts/svaras-siddhaanta.html>

**Comment by vvasuki** [comment]
"user must set up some font on his device to view my website properly" इति हेयो मार्ग इत्येव ब्रूमहे।
