### ISSUE TITLE
Switch template?

### ISSUE THREAD

**Issue by vvasuki** [aupasana/prayoga#2]
Currently, your site is presumably not indexed by google, leading to:
- intra-site search not being possible at github.io.
- the site not showing up in google searches.

Why don't you switch to and tweak [this jekyll template](https://github.com/sanskrit-coders/site)? Bonus will be that you get many more cool features like dropdown content navigation, table of contents, "edit-me" links etc..

**Comment by aupasana** [comment]
Many will use PDFs generated from this site as the primary format in the future. All the cool features will get in the way at that point. I will submit the sub site to search engines once there is more content here.

If someone wants to make the template changes, I’d be happy to consider it, but I’m not sold on it. And I don’t have the time to work on it in the near future. There is more fundamental work to be done ... like making sure it all renders correctly on iOS on some browser.

**Comment by vvasuki** [comment]
Just curious - how does https://sanskrit-coders.github.io/site/ (which uses that template) render on iOS? Any problems?

**Comment by vvasuki** [comment]
Also regarding pdf generation or more simply "printing a given page on the site, as displayed on the browser" (which is what I think you mean)  - Some simple modifications to the template may remove formatting problems - removing the side menu but keeping the top drop-down and intra-page table of contents.

PS: In case you would convert multiple web pages on your site to a pdf one can dynamically generate a page with these other pages and then convert it to a pdf. Also, there seem to be a few gems/ plugins/ sites to generate pdfs directly from markdown.

**Comment by aupasana** [comment]
Everything you are talking about is possible, but requires work ... unfortunately, that simply isn't high on my priority list. As far as pdf generation goes, only chrome renders it without errors (at least, that's the only browser on which I have yet to see issues), so the pdf has to come from chrome in headless mode, or some headless fork ... everything else has rendering issues with the siddhanta based fonts and swaras.

**Comment by vvasuki** [comment]
Switching to the template I suggested with the modifications I mentioned will be very easy for me. यदि तवाङ्गीकारोऽस्ति, श्रमो न व्यर्थो भविष्यतीत्यवगत्य तद्विधास्यामि (यतो हि ममाभीष्टानीमानि परिवर्तनानि)। त्वदनुज्ञाम् एव प्रतीक्षे। I will also add custom stuff like siddhAnta font usage - could you list other modifications you've made? (or you can mention/ do it later.)

**Comment by aupasana** [comment]
I'd like to keep this on the default gh-pages template for now. I've added 'edit' links on the top, and toc for a few of the pages (when appropriate). If there are specific things you want added, let me know.
